apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{  .Chart.Name }}-pvc"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  storageClassName: {{ .Values.storage.classname }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}

